### PR TITLE
changed plugin.yml

### PR DESCRIPTION
**Pull request by harvey298**
very very small change

on another note, why for spigot? imo I feel like it should be a paper plugin

### CODE REVIEW

**Comment by LockedThread** [comment]
Paper is a spigot fork...

**Comment by Skyslycer** [comment]
> 
> 
> Paper is a spigot fork...

even if, the Paper API has some neat features that could be used here.
Also, this thing is going for perfomance. The first step for perfomance is switching to Paper

**Comment by HookWoods** [comment]
Or can use [https://github.com/PaperMC/PaperLib](url) so like that people with spigot could still use spigot if they don't want to switch to paper, and people with paper can use paper part

**Comment by LockedThread** [comment]
> > 
> 
> > 
> 
> > Paper is a spigot fork...
> 
> 
> 
> even if, the Paper API has some neat features that could be used here.
> 
> Also, this thing is going for perfomance. The first step for perfomance is switching to Paper

Seems like the user's problem if they don't use paper... a plugin shouldn't be the one enforcing that.

**Comment by harvey298** [comment]
> > > 
> > 
> > 
> > > 
> > 
> > 
> > > Paper is a spigot fork...
> > 
> > 
> > even if, the Paper API has some neat features that could be used here.
> > Also, this thing is going for perfomance. The first step for perfomance is switching to Paper
> 
> Seems like the user's problem if they don't use paper... a plugin shouldn't be the one enforcing that.

if I'm correct spigot still uses legacy chat with Mojang deprecated years ago (7 I think)

**Comment by Jaxkr** [comment]
Thank you Harvey, merges.

**Pull request merged**
